/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.ivanrodrigues.medflow.ui;

import dev.ivanrodrigues.medflow.controller.AppUIController;
import dev.ivanrodrigues.medflow.ui.layouts.Login;
import dev.ivanrodrigues.medflow.ui.layouts.Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JMenuItem;

/**
 *
 * @author ivan8505
 */
public class AppUI extends javax.swing.JFrame {

    private final Main main;
    private AppUIController appc;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppUI.class.getName());

    /**
     * Creates new form App
     */
    public AppUI() {
        initComponents();
        this.main = new Main();
        this.appc = new AppUIController(main, this);
        login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenuItem64 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Med Flow");
        setExtendedState(MAXIMIZED_BOTH);

        jMenu1.setText("User");

        jMenuItem1.setText("Log out");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenu8.setText("Switch User");

        jMenuItem2.setText("Other user");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu8.add(jMenuItem2);

        jMenu1.add(jMenu8);

        jMenu9.setText("Profile");

        jMenuItem3.setText("Change Password");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu9.add(jMenuItem3);

        jMenuItem5.setText("Edit User");
        jMenu9.add(jMenuItem5);

        jMenuItem4.setText("Show Profile");
        jMenu9.add(jMenuItem4);

        jMenu1.add(jMenu9);

        jMenu10.setText("Admin");

        jMenuItem6.setText("Create User");
        jMenu10.add(jMenuItem6);

        jMenuItem7.setText("Edit User");
        jMenu10.add(jMenuItem7);

        jMenuItem8.setText("Delete User");
        jMenu10.add(jMenuItem8);

        jMenuItem9.setText("Manage Permissions");
        jMenu10.add(jMenuItem9);

        jMenuItem10.setText("Block/Unblock User");
        jMenu10.add(jMenuItem10);

        jMenuItem11.setText("Audit / Acess Logs");
        jMenu10.add(jMenuItem11);

        jMenuItem12.setText("Activity History");
        jMenu10.add(jMenuItem12);

        jMenuItem13.setText("Advanced Settings");
        jMenu10.add(jMenuItem13);

        jMenu1.add(jMenu10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administration");

        jMenuItem14.setText("System Settings");
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Backup Data");
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Restore Backup");
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Manage Acess");
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Define Roles and Profiles");
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("Discount / Promotion Rules");
        jMenu2.add(jMenuItem19);

        jMenuItem20.setText("General Audit");
        jMenu2.add(jMenuItem20);

        jMenuItem21.setText("Operation Logs");
        jMenu2.add(jMenuItem21);

        jMenuItem22.setText("Financial Reports");
        jMenu2.add(jMenuItem22);

        jMenuItem23.setText("Sales Reports");
        jMenu2.add(jMenuItem23);

        jMenuItem24.setText("Inventory Reports");
        jMenu2.add(jMenuItem24);

        jMenuItem25.setText("System Alerts and Notifications");
        jMenu2.add(jMenuItem25);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Inventory");

        jMenuItem26.setText("List Products");
        jMenu3.add(jMenuItem26);

        jMenuItem27.setText("Add Product");
        jMenu3.add(jMenuItem27);

        jMenuItem28.setText("Remove Product");
        jMenu3.add(jMenuItem28);

        jMenuItem29.setText("Product Categories");
        jMenu3.add(jMenuItem29);

        jMenuItem30.setText("Suppliers");
        jMenu3.add(jMenuItem30);

        jMenuItem31.setText("Batches / Expiration");
        jMenu3.add(jMenuItem31);

        jMenuItem32.setText("Low Stock Alerts");
        jMenu3.add(jMenuItem32);

        jMenuItem33.setText("Near - Expiration Alerts");
        jMenu3.add(jMenuItem33);

        jMenuItem34.setText("Stock Movements");
        jMenu3.add(jMenuItem34);

        jMenuItem35.setText("Inventory Reports");
        jMenu3.add(jMenuItem35);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Purchases");

        jMenuItem36.setText("Register Purchase");
        jMenu4.add(jMenuItem36);

        jMenuItem37.setText("Create Purchase Order");
        jMenu4.add(jMenuItem37);

        jMenuItem38.setText("Edit Purchase Order");
        jMenu4.add(jMenuItem38);

        jMenuItem39.setText("Cancel Purchase Order");
        jMenu4.add(jMenuItem39);

        jMenuItem41.setText("Approve Purchase");
        jMenu4.add(jMenuItem41);

        jMenuItem42.setText("Suppliers");
        jMenu4.add(jMenuItem42);

        jMenuItem43.setText("Acconts Payable");
        jMenu4.add(jMenuItem43);

        jMenuItem44.setText("Stock Entry");
        jMenu4.add(jMenuItem44);

        jMenuItem45.setText("Puchase Reports");
        jMenu4.add(jMenuItem45);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sales");

        jMenuItem46.setText("Register Sale");
        jMenu5.add(jMenuItem46);

        jMenuItem47.setText("Cancel Sale");
        jMenu5.add(jMenuItem47);

        jMenuItem48.setText("Refund Sale");
        jMenu5.add(jMenuItem48);

        jMenuItem49.setText("Cash Register");
        jMenu5.add(jMenuItem49);

        jMenuItem50.setText("Cash Closing");
        jMenu5.add(jMenuItem50);

        jMenuItem51.setText("Payment Methods");
        jMenu5.add(jMenuItem51);

        jMenuItem52.setText("Apply Discounts");
        jMenu5.add(jMenuItem52);

        jMenuItem53.setText("Sales History");
        jMenu5.add(jMenuItem53);

        jMenuItem54.setText("Sales by Employee");
        jMenu5.add(jMenuItem54);

        jMenuItem55.setText("Sales Reports");
        jMenu5.add(jMenuItem55);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Customers");

        jMenuItem56.setText("Register Customer");
        jMenu6.add(jMenuItem56);

        jMenuItem57.setText("Edit Customer");
        jMenu6.add(jMenuItem57);

        jMenuItem58.setText("List Customers");
        jMenu6.add(jMenuItem58);

        jMenuItem59.setText("Remove Customer");
        jMenu6.add(jMenuItem59);

        jMenuItem61.setText("Purchase History");
        jMenu6.add(jMenuItem61);

        jMenuItem62.setText("Loyalty Program");
        jMenu6.add(jMenuItem62);

        jMenuItem63.setText("Credits / Debits");
        jMenu6.add(jMenuItem63);

        jMenuItem64.setText("Health Plans / Agreements");
        jMenu6.add(jMenuItem64);

        jMenuItem65.setText("Block / Unblock Customer");
        jMenu6.add(jMenuItem65);

        jMenuItem66.setText("Customer Reports");
        jMenu6.add(jMenuItem66);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Reports");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        logout();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        editPassword();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppUI().setVisible(true));
    }

    /*
    //<editor-fold defaultstate="collapsed" desc=" Variaveis criadas automaticamente com Netbeans ">
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

    //Code criado por MIM ivan8505
    private void login() {
        jMenuBar1.setVisible(false);
        appc.registerPanels("Login", new Login(appc));
        add(main);

        appc.showPanel("Login");

        setTitle("Med Flow - Login");
    }

    private void logout() {
        jMenuBar1.setVisible(false);
        appc.registerPanels("Login", new Login(appc));
        appc.showPanel("Login");
    }

    private void editPassword() {
        appc.editPassword();
    }

    public void accessAdmin() {
        jMenuBar1.setVisible(true);
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void levelAccess(String user) {
        if ("other user".equals(user)) {
            appc.registerPanels("Login", new Login(appc));
            appc.showPanel("Login");
        } else {
            
        }
    }

    public void setSessionMenuBar(ArrayList<String> usernames) {
        jMenu8.removeAll(); // opcional, limpa itens antigos

        for (String name : usernames) {
            JMenuItem item = new JMenuItem(name);
            jMenu8.add(item);
            item.addActionListener((ActionEvent e) -> {
                levelAccess(name);
            });
        }
        jMenu8.revalidate(); // atualiza o menu
        jMenu8.repaint();
    }

}
