/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package dev.ivanrodrigues.medflow.ui;

/**
 *
 * @author ivan8505
 */

public class AppUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppUI.class.getName());

    /**
     * Creates new form AppUI
     */
    
    public AppUI() {
        initComponents();
        jMenuBar2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        login1 = new dev.ivanrodrigues.medflow.ui.layouts.Login();
        pageAdmin1 = new dev.ivanrodrigues.medflow.ui.layouts.PageAdmin();
        pageAdmin2 = new dev.ivanrodrigues.medflow.ui.layouts.PageAdmin();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setExtendedState(this.MAXIMIZED_BOTH);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 319;
        gridBagConstraints.ipady = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(150, 200, 150, 200);
        getContentPane().add(login1, gridBagConstraints);

        javax.swing.GroupLayout pageAdmin1Layout = new javax.swing.GroupLayout(pageAdmin1);
        pageAdmin1.setLayout(pageAdmin1Layout);
        pageAdmin1Layout.setHorizontalGroup(
            pageAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pageAdmin1Layout.setVerticalGroup(
            pageAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pageAdmin1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout pageAdmin2Layout = new javax.swing.GroupLayout(pageAdmin2);
        pageAdmin2.setLayout(pageAdmin2Layout);
        pageAdmin2Layout.setHorizontalGroup(
            pageAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pageAdmin2Layout.setVerticalGroup(
            pageAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pageAdmin2, new java.awt.GridBagConstraints());

        jMenu3.setText("User");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Administration");
        jMenuBar2.add(jMenu4);

        jMenu1.setText("Dashboard");
        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private dev.ivanrodrigues.medflow.ui.layouts.Login login1;
    private dev.ivanrodrigues.medflow.ui.layouts.PageAdmin pageAdmin1;
    private dev.ivanrodrigues.medflow.ui.layouts.PageAdmin pageAdmin2;
    // End of variables declaration//GEN-END:variables

    //Code criado por MIM ivan8505
    public void admin(){
        jMenuBar2.setVisible(true);
    }



}
