package dev.ivanrodrigues.medflow.ui.layouts;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ivan8505
 */
public class Main extends javax.swing.JPanel {

    private final CardLayout layout;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        layout = new CardLayout();
        setLayout(layout);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void register(String name, JPanel panel) {
        add(panel, name);
    }

    public void show(String card) {
        layout.show(this, card);
    }

}
